phraseapp:
  access_token: <your_access_token>
  project_id: <your_project_id>
  push:
    sources:
    - file: ./en.lproj/Localizable.strings
      params:
        locale_id: <your_en_locale_id>
        file_format: strings
  pull:
    targets:
    - file: ./ar.lproj/Localizable.strings
      params:
        locale_id: <your_ar_locale_id>
        file_format: strings
